<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\CubeTrainer.Application\CubeTrainer.Application.csproj" />
    <ProjectReference Include="..\CubeTrainer.Infrastructure\CubeTrainer.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(OfflineBuild)' != 'true'">
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
  </ItemGroup>

  <Import Project="..\..\build\OfflineIdentityModel.props" />

  <PropertyGroup Condition="'$(OfflineBuild)' != 'true'">
    <DefineConstants>$(DefineConstants);OPENAPI</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CubeTrainer.IntegrationTests" />
  </ItemGroup>
</Project>
